# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "run UnitTestDemoTests and output report"
  lane :UnitTestDemoTests do
    # add actions here: https://docs.fastlane.tools/actions
    run_tests(scheme: "UnitTestDemoTests",
              clean: true,
              fail_build: false,
              configuration: "Debug",
              output_types: "html,junit",
              output_files: "UnitTestDemoTests.html, UnitTestDemoTests.xml")
   end

  desc "run OCLint and output report"
  lane :UnitTestDemoLint do
    # add actions here: https://docs.fastlane.tools/actions
    sh "cd .. && chmod 777 oclint.sh && ./oclint.sh"
    #sh "cd .. && chmod 777 Infer_PMD.sh && ./Infer_PMD.sh UnitTestDemo UnitTestDemo 2"
   end
end
